<template>
  <div id="adblock-main">
    <div class="container-wrapper">

      <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <main role="main" class="inner cover text-center">
          <h1 class="cover-heading">Sorry to interrupt your flow. But...</h1>
          <p class="lead-light">
            Our team of Researchers, Programmers and Copywriters worked hard to bring you this information. We depend on the
            tiny bit of revenue generated by ads to keep running this site.
          </p>
          <p class="lead-light">Your adblocker is running. Please disable it to continue.</p>
          <p class="lead-light">
            <!-- <a href="index.html" class="btn btn-lg btn-outline-info">My adblocker is disabled. Return to article. </a> -->

            <router-link
              to="/"
              class="btn btn-lg btn-outline-info"
            >My adblocker is disabled. Return to article.</router-link>
          </p>
          <p class="lead-light">
            <a
              href="https://google.com/"
              target="_blank"
              class="white-text"
            >No thanks. I'll go elsewhere.</a>
          </p>
        </main>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "adblock",
  components: "",

  created() {},
  mounted() {},
  beforeRouteLeave(to, from, next) {
    console.log("Logging route to ...", to);
    console.log("Logging route from ...", from.name);

    if (from.name == "adblock" && to.name == "home") {
      if (document.getElementById("369379917555767") == undefined) {
        next(false);
      } else {
        next();
      }
    } else {
      next();
    }
  }
};
</script>

<style scoped>
@import "../assets/styles/cover.css";

a {
  text-decoration: none;
}

a.white-text {
  color: #fff;
}

#adblock-main {
  height: 100%;
  background: url("../assets/img/dev_revenue1.jpg");
  background-size: cover;
  background-repeat: no-repeat;
  min-height: 800px;
}

</style>
