<template>
  <div id="adblock-main">
    <div class="container-wrapper">
      <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <main role="main" class="inner cover text-white text-center">
          <div class="container">
            <div class="row">
              <div class="col col-lg-8 offset-lg-2 col-md-12">
                <h1 class="text-white">
                  Sorry to interrupt your flow.
                  <br />But...
                </h1>
                <hr />
                <p class="lead-light">
                  Our team of Researchers, Programmers and Copywriters worked hard to bring you this information. <em> We depend on the
                  tiny bit of revenue generated by ads to keep running this site. </em>
                </p>
                <p class="lead-light">We see that you have an adblocker running. <span class="highlight"> Please disable it</span> to continue reading the article.</p>
              </div>
            </div>
          </div>

          <p class="lead-light">
            <router-link
              to="/"
              class="btn btn-lg btn-outline-info"
            >My adblocker is disabled. Return to article.</router-link>
          </p>
          <p class="lead-light">
            <a
              href="https://google.com/"
              target="_blank"
              class="white-text"
            >No thanks. I'll go elsewhere.</a>
          </p>
        </main>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "adblock",
  components: "",

  created() {},
  mounted() {},
  beforeRouteLeave(to, from, next) {
    console.log("Logging route to ...", to);
    console.log("Logging route from ...", from.name);

    if (from.name == "adblock" && to.name == "home") {
      if (document.getElementById("369379917555767") == undefined) {
        next(false);
      } else {
        next();
      }
    } else {
      next();
    }
  }
};
</script>

<style scoped>
@import "../assets/styles/cover.css";

a {
  text-decoration: none;
}

a.white-text {
  color: #fff;
}

.highlight {
  color: orange;
}

#adblock-main {
  height: 100%;
  background: url("../assets/img/dev_revenue1.jpg");
  background-size: cover;
  background-repeat: no-repeat;
  min-height: 800px;
}

/* Extra small devices (portrait phones, less than 576px)
No media query since this is the default in Bootstrap */

/* Small devices (landscape phones, 576px and up) */
@media (max-width: 576px) {
  p {
    font-size: 0.95rem;
  }
  h1 {
    font-size: 2.5rem;
  }

}

/* Medium devices (tablets, 768px and up) */
@media (max-width: 768px) {
  h1 {
    font-size: 2.3rem;
  }

}

/* Large devices (desktops, 992px and up) */
@media (min-width: 992px) {
  /* main {
    width: 60%;
  } */
}
@media (max-width: 991px) {
}

/* Extra large devices (large desktops, 1200px and up) */
@media (min-width: 1200px) {
}
</style>
